```plain
$pip install tensorflow
```
https://www.tensorflow.org/install/pip?hl=ko

In [173]:
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

print(tensorflow.__version__)

2.17.0


In [174]:
mnist = tf.keras.datasets.mnist # 8비트 이미지이다.

In [175]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [176]:
X_train[0].shape

(28, 28)

In [177]:
y_train[0].shape

()

8비트 회색조 이미지, 

28x28px 크기, 

총 데이터 7만개. 6:1 비율로 train-test split

총 10개 클래스

min-max scale 을 해준다. 

이미지의 경우는 255로 나눈다.

In [178]:
(X_train/255)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [179]:
X_train[0].max()

255

In [180]:
X_train[0].min()

0

In [181]:
set(y_test)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [182]:
X_train = X_train/255.0
X_test = X_test/255.0

### 딥러닝 모델 만들기

1. 모델 정의(어떤 형태의 모델을 구현할 것인가)

In [183]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),  # 입력층 
        tf.keras.layers.Dense(128,activation='relu'),   # 입력 레이어, 출력 레이어를 연결해주는 레이어
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax') # 출력층
    ]
)

2. 모델 컴파일

In [184]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

3. 예측

In [185]:
X_train[0:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [186]:
predictions = model(X_train[2:3])

In [187]:
predictions.numpy()

array([[0.08089913, 0.04784371, 0.09346858, 0.1031269 , 0.17007236,
        0.0787237 , 0.09242349, 0.09350286, 0.12500753, 0.11493175]],
      dtype=float32)

In [188]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [189]:
tf.nn.softmax(predictions).numpy()

array([[0.09806136, 0.09487289, 0.09930171, 0.10026545, 0.10720754,
        0.09784827, 0.09919799, 0.09930512, 0.1024835 , 0.10145608]],
      dtype=float32)

In [190]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[2:3],predictions).numpy()

1.7715313

모델 학습

In [191]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8545 - loss: 0.5025
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9532 - loss: 0.1551
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9676 - loss: 0.1046
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9725 - loss: 0.0907
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9761 - loss: 0.0748
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9803 - loss: 0.0628
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9818 - loss: 0.0584
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9829 - loss: 0.0526
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9843 - loss: 0.0466
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9870 - loss: 0.0408


In [192]:
model.evaluate(X_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.9752 - loss: 0.0906


[0.07757880538702011, 0.9793000221252441]

In [195]:
model.predict(X_train[18:20])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[2.7050442e-06, 1.2261754e-07, 4.1371109e-07, 3.2508301e-06,
        3.8017558e-07, 6.9875969e-04, 9.9804902e-01, 1.7223919e-09,
        1.2301110e-03, 1.5339359e-05],
       [1.2548747e-10, 2.2100289e-07, 5.2370680e-10, 1.0196186e-03,
        4.9867817e-06, 2.1073961e-06, 1.7651099e-13, 8.5496802e-05,
        3.3867725e-06, 9.9888426e-01]], dtype=float32)