y = 2x+1 과 거의 똑같아졌다.

W = 2 , y = 1

In [37]:
import tensorflow as tf
import numpy as np

# 데이터 생성 (y = 2x + 1)
X = np.array([1, 2, 3, 4], dtype=np.float32)
y = np.array([3, 5, 7, 9], dtype=np.float32)

# 가중치, 바이어스 초기화
W = tf.Variable(0.0)
b = tf.Variable(0.0)

def linear_model(X):
    return W * X + b

def mean_squared_error(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# root_mean_squared_error 수정: math.sqrt 대신 tf.sqrt 사용
def root_mean_squared_error(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_true - y_pred)))

def mean_absolute_error(y_true,y_pred):
    return tf.abs(tf.reduce_mean(y_true - y_pred))

optimizer = tf.optimizers.SGD(learning_rate=0.01)

# 학습 과정 정의
def train_step(X, y):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = mean_squared_error(y, y_pred)
    gradients = tape.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return loss

# root_train_step 수정
def root_train_step(X, y):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = root_mean_squared_error(y, y_pred)
    gradients = tape.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return loss

# root_train_step 수정
def mae_root_train_step(X, y):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = mean_absolute_error(y, y_pred)
    gradients = tape.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return loss

# 학습 반복
epochs = 300
for epoch in range(epochs):
    # loss = root_train_step(X, y)
    # loss = train_step(X, y)
    loss = mae_root_train_step(X, y)
    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss: {loss.numpy()}")

# 학습된 파라미터 출력
print(f"학습된 W: {W.numpy()}")
print(f"학습된 b: {b.numpy()}")

# 예측 결과 출력
X_test = np.array([5, 6], dtype=np.float32)
y_test_pred = linear_model(X_test)
print(f"예측 결과: {y_test_pred.numpy()}")


Epoch 0: Loss: 6.0
Epoch 10: Loss: 5.275000095367432
Epoch 20: Loss: 4.549999713897705
Epoch 30: Loss: 3.825000524520874
Epoch 40: Loss: 3.1000008583068848
Epoch 50: Loss: 2.3750016689300537
Epoch 60: Loss: 1.6500022411346436
Epoch 70: Loss: 0.9250029921531677
Epoch 80: Loss: 0.20000362396240234
Epoch 90: Loss: 0.055003464221954346
Epoch 100: Loss: 0.055003464221954346
Epoch 110: Loss: 0.055003464221954346
Epoch 120: Loss: 0.055003464221954346
Epoch 130: Loss: 0.055003464221954346
Epoch 140: Loss: 0.055003464221954346
Epoch 150: Loss: 0.055003464221954346
Epoch 160: Loss: 0.055003464221954346
Epoch 170: Loss: 0.055003464221954346
Epoch 180: Loss: 0.055003464221954346
Epoch 190: Loss: 0.055003464221954346
Epoch 200: Loss: 0.055003464221954346
Epoch 210: Loss: 0.055003464221954346
Epoch 220: Loss: 0.055003464221954346
Epoch 230: Loss: 0.055003464221954346
Epoch 240: Loss: 0.055003464221954346
Epoch 250: Loss: 0.055003464221954346
Epoch 260: Loss: 0.055003464221954346
Epoch 270: Loss: 0.0

---


In [38]:
y_true = np.array([[0,1,0],[1,0,0],[0,1,0]])
y_pred = np.array([[0.1,0.7,0.2],[0.8,0.1,0.15],[0.2,0.6,0.3]])

In [41]:
tf.keras.losses.categorical_crossentropy(y_true,y_pred)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.35667494, 0.27193372, 0.6061358 ])>

In [42]:
tf.reduce_mean(tf.abs(y_true-y_pred))

<tf.Tensor: shape=(), dtype=float64, numpy=0.21666666666666667>

In [43]:
tf.reduce_mean(tf.square(y_true-y_pred))

<tf.Tensor: shape=(), dtype=float64, numpy=0.05583333333333334>

In [44]:
tf.sqrt(tf.reduce_mean(tf.square(y_true-y_pred)))

<tf.Tensor: shape=(), dtype=float64, numpy=0.23629078131263043>